### PR TITLE
Bump gvisor & wireguard to support Go 1.22

### LINKED ISSUE #3145: Support Go 1.22
Trying to build with Go 1.22
* https://github.com/Homebrew/homebrew-core/pull/157782

fails with errors:

````
  # gvisor.dev/gvisor/pkg/sync
  /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/gate_unsafe.go:114:3: undefined: goready
  /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/gate_unsafe.go:144:2: undefined: gopark
  /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/rwmutex_unsafe.go:76:3: undefined: semacquire
  /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/rwmutex_unsafe.go:102:4: undefined: semrelease
  /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/rwmutex_unsafe.go:152:3: undefined: semacquire
  /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/rwmutex_unsafe.go:179:3: undefined: semrelease
  /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/rwmutex_unsafe.go:207:3: undefined: semrelease
  /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/seqcount.go:87:6: undefined: canSpin
  /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/seqcount.go:89:4: undefined: doSpin
````

Currently it is using gvisor from May 2023:
https://github.com/superfly/flyctl/blob/363a4dd4b22920ae0779c67208040d45c565d817/go.mod#L178

Likely the solution is to bump to newer (or latest) version of `gvisor.dev/gvisor` to include also Go 1.22 support from July 2023:
* https://github.com/google/gvisor/pull/9197

Similar gvisor bump was needed for Go 1.21:
* https://github.com/superfly/flyctl/issues/2688
* https://github.com/superfly/flyctl/pull/2727

### PR DESCRIPTION
**Pull request by stefanb**
### Change Summary

Add support for Go 1.22 by bumping `gvisor.dev/gvisor` and `golang.zx2c4.com/wireguard`

What and Why:
When trying to build with Go 1.22rc1 it failed:
````
$ make build                                 
Running Generate for Help and GraphQL client
go1.22rc1 generate ./...
Running Build
CGO_ENABLED=0 go1.22rc1 build -o bin/flyctl -ldflags="-X 'github.com/superfly/flyctl/internal/buildinfo.buildDate=2024-01-06T22:18:05Z' -X 'github.com/superfly/flyctl/internal/buildinfo.branchName=master'" .
# gvisor.dev/gvisor/pkg/sync
../../../go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/gate_unsafe.go:114:3: undefined: goready
../../../go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/gate_unsafe.go:144:2: undefined: gopark
../../../go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/rwmutex_unsafe.go:76:3: undefined: semacquire
../../../go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/rwmutex_unsafe.go:102:4: undefined: semrelease
../../../go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/rwmutex_unsafe.go:152:3: undefined: semacquire
../../../go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/rwmutex_unsafe.go:179:3: undefined: semrelease
../../../go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/rwmutex_unsafe.go:207:3: undefined: semrelease
../../../go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/seqcount.go:87:6: undefined: canSpin
../../../go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/seqcount.go:89:4: undefined: doSpin
make: *** [build] Error 1
````

Go 1.22 support was added to `gvisor.dev/gvisor` in: 
* https://github.com/google/gvisor/pull/9197

How:

Because `gvisor.dev/gvisor` [API changed](https://github.com/google/gvisor/commit/c006f01e0e550ea5609190131747d7b1533f8e03) slightly and is referenced via `golang.zx2c4.com/wireguard` I ran:
````
go get golang.zx2c4.com/wireguard@latest
go mod tidy
````

The build then succeeded:
````
$ make build
Running Generate for Help and GraphQL client
go1.22rc1 generate ./...
Running Build
CGO_ENABLED=0 go1.22rc1 build -o bin/flyctl -ldflags="-X 'github.com/superfly/flyctl/internal/buildinfo.buildDate=2024-01-06T22:24:52Z' -X 'github.com/superfly/flyctl/internal/buildinfo.branchName=go1.22'" .
````

Related to:
* Fixes #3145

---

### Documentation

- [ ] Fresh Produce
- [ ] In superfly/docs, or asked for help from docs team
- [x] n/a

### CODE REVIEW

**Comment by stefanb** [comment]
@dangra you're welcome!
Please don't forget to tag & release a version once everything else is ready.

**Comment by dangra** [comment]
Good call and sorry for the delay. v0.1.140 is on its way to be a new release.
