### ISSUE TITLE
Support Go 1.22

### ISSUE THREAD

**Issue by stefanb** [superfly/flyctl#3145]
Trying to build with Go 1.22
* https://github.com/Homebrew/homebrew-core/pull/157782

fails with errors:

````
  # gvisor.dev/gvisor/pkg/sync
  /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/gate_unsafe.go:114:3: undefined: goready
  /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/gate_unsafe.go:144:2: undefined: gopark
  /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/rwmutex_unsafe.go:76:3: undefined: semacquire
  /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/rwmutex_unsafe.go:102:4: undefined: semrelease
  /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/rwmutex_unsafe.go:152:3: undefined: semacquire
  /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/rwmutex_unsafe.go:179:3: undefined: semrelease
  /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/rwmutex_unsafe.go:207:3: undefined: semrelease
  /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/seqcount.go:87:6: undefined: canSpin
  /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/sync/seqcount.go:89:4: undefined: doSpin
````

Currently it is using gvisor from May 2023:
https://github.com/superfly/flyctl/blob/363a4dd4b22920ae0779c67208040d45c565d817/go.mod#L178

Likely the solution is to bump to newer (or latest) version of `gvisor.dev/gvisor` to include also Go 1.22 support from July 2023:
* https://github.com/google/gvisor/pull/9197

Similar gvisor bump was needed for Go 1.21:
* https://github.com/superfly/flyctl/issues/2688
* https://github.com/superfly/flyctl/pull/2727

**Comment by stefanb** [comment]
Proposed fix implemented in #3161
